version: '3'

services:
  app:
    build: ./app
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: docker

  web:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/kniffel?sslmode=disable
    ports:
        - 8080:8081
volumes:
  db:
